### ISSUE TITLE
Metaconstants mentioned in prerequisite print as functions

### ISSUE THREAD

**Issue by tcrayford** [marick/Midje#195] opened 2013-03-13 01:44 UTC
``` clojure
(fact "metaconstants mentioned in prerequisites print"
  (prerequisite
    (...an-fn...) => ...ignored...)
  (prn ...an-fn...) => nil)

; prints:
; #< clojure.lang.AFunction$1@5a08f27c>
```

**Comment by phillipm** [comment] 2017-11-13 15:49
Closing out because printing the function object is expected behavior.

Regarding the example in 
https://github.com/marick/Midje/issues/195#issuecomment-19323103, it seems like what you described as expected behavior is what Midje currently does. If I'm missing a nuance, let me know.

**Closed by phillipm** 2017-11-13 15:49 UTC
Labels: wishlist
